### ISSUE TITLE
Example command is not working

### ISSUE THREAD

**Issue by cemsbr** [tizonia/docker-tizonia#1]
I cannot get docker-tizonia to work. I'm using the wrapper and this is the result:
```
$ docker-tizonia --youtube-audio-mix-search "Queen Official"
tizonia 0.11.0. Copyright (C) 2017 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

```
It takes less than a second. `--youtube-audio-stream` has the same behavior.

**Comment by juanrubio** [comment]
Hi!,

Thanks for trying the software. It seems to work on my Ubuntu 16.04 machine. Would you able to share some other details like OS etc?

**Comment by cemsbr** [comment]
I'm running Debian testing (buster). Docker version 17.12.0-ce, build c97c6d6.

**Comment by tizonia** [comment]
Hi @cemsbr 

This is a very old issue (apologies for that). The docker-tizonia was updated some time back, do you know if this is still an issue?

**Comment by cemsbr** [comment]
It's working now, though it started playing "Hotel California" :).
