### ISSUE TITLE
Unable to use for machine without audio devices, workaround failed as well

### ISSUE THREAD

**Issue by evilmtv** [tizonia/docker-tizonia#13]
### Description

There are no hardware sound cards/devices available as it is a cloud server that I'm testing this out on. As such I've created a dummy hardware device using `sudo modprobe snd-dummy` for Alsa.
Trying to stream a Spotify song gives this error:
```bash
tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_renderer.alsa.pcm:port:0]
 [OMX_ErrorInsufficientResources]
```
I'm not sure if its because of my setup or I've wrongly configured `~/.config/spotifyd/spotifyd.conf`.
Or is there a cleaner way to do this by tinkering with the source code itself and allowing for no audio output?

### Steps to Reproduce

```bash
# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: Dummy [Dummy], device 0: Dummy PCM [Dummy PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice tizonia/tizonia-openmax-il#1: subdevice tizonia/tizonia-openmax-il#1
  Subdevice tizonia/tizonia-openmax-il#2: subdevice tizonia/tizonia-openmax-il#2
  Subdevice tizonia/tizonia-openmax-il#3: subdevice tizonia/tizonia-openmax-il#3
  Subdevice tizonia/tizonia-openmax-il#4: subdevice tizonia/tizonia-openmax-il#4
  Subdevice tizonia/tizonia-openmax-il#5: subdevice tizonia/tizonia-openmax-il#5
  Subdevice tizonia/tizonia-openmax-il#6: subdevice tizonia/tizonia-openmax-il#6
  Subdevice tizonia/tizonia-openmax-il#7: subdevice tizonia/tizonia-openmax-il#7 
```

Config file: 
```bash
[plugins]
# OpenMAX IL Component plugins section

# Each key-value pair represents a list of any data that a
# specific component might need. The entries here must honor the following
# format: OMX.component.name.key = <semi-colon-separated list of items>

# ALSA Audio Renderer
# -------------------------------------------------------------------------
#
# OMX.Aratelia.audio_renderer.alsa.pcm.preannouncements_disabled.port0 = false
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_device = Dummy
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_mixer = Dummy PCM


[tizonia]
# Tizonia player section

# The default audio renderer used by the tizonia player
# -------------------------------------------------------------------------
# Valid values are:
# - OMX.Aratelia.audio_renderer.pulseaudio.pcm
# - OMX.Aratelia.audio_renderer.alsa.pcm
default-audio-renderer = OMX.Aratelia.audio_renderer.alsa.pcm
```
Did I name the device and mixer wrongly?

**Expected behavior:** Able to play into the void

**Actual behaviour:** Doesn't play into the void :(

**Reproduces how often:** 100%

### Versions

```bash
# docker-tizonia --version
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

# docker-tizonia --debug
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
            * [Boost 1_65_1]
            * [TagLib 1.11.1]
            * [MediaInfoLib - v17.12]
```

```bash
# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### Installation Method Used

Docker

### Additional Information

Note: Running as root instead of a normal user. This gave problems with PulseAudio leaving me with Alsa. Tried to run in both desktop (RDP) and ssh.

**Comment by evilmtv** [comment]
1. With regards to the 'having to run docker as non-root user' issue, could it be a result of the user permissions:
https://github.com/tizonia/docker-tizonia/blob/1000fcd6c4fb54c634096dff880a7b560c7820ae/Dockerfile#L97-L100
I did not test if removing this would solve the issue. Is this a common security practice or something? (Apologies, I'm unfamiliar with these)

2. I was able to easily update the Dockerfile for 0.19.0, however the method may not be your intention.
What I did was first downloading the latest `install.sh` file from https://github.com/tizonia/tizonia-openmax-il/blob/master/tools/install.sh and manually removing all the `sudo` and `sudo -H` from the bash script to let it run when building the Docker image. I added this modified script to the directory where `Dockerfile` resides and added a line to `Dockerfile`
```bash
# Copy Install script
COPY install.sh /install.sh
```
I removed these lines:
https://github.com/tizonia/docker-tizonia/blob/1000fcd6c4fb54c634096dff880a7b560c7820ae/Dockerfile#L50-L72
And ran the modified script with no issues when building the image:
```bash
&& chmod +x install.sh && ./install.sh --safe \
```
Perhaps this could be done automatically by pulling the latest of install.sh and removing the relevant `sudo` `sudo -H` phrases.


I didn't make a pull request as I'm not sure if you'd be okay with this method. If it's A-OK i'll test it again and add a PR

**Comment by tizonia** [comment]
Hi Jun,

Apologies for the delay. I appreciate your efforts. I'm currently busy finishing up a new release of Tizonia in the main repo. If @Josh5  hasn't got a chance to look at it when I'm finished, then I will try to refresh the docker image with the latest and greatest. Hopefully, we will get things working again soon.

**Comment by evilmtv** [comment]
Hi, saw that you've updated it to v0.20.0.
I'll work on updating the `Dockerfile`. Figured there's no need to do it the way I suggested and keep it in line with the current method instead.

**Comment by tizonia** [comment]
Awesome! I really struggle to keep up with all the packaging and porting activities (debian, AUR, snap, macos, docker). Docker has always been at the bottom of the list I have to admit.

So your PR will be most welcome!

**Comment by matthewarmand** [comment]
@evilmtv , I've been playing around with an update to the Dockerfile in my fork at https://github.com/matthewarmand/docker-tizonia/tree/python3-tiz19-upgrade. I've gotten  it mostly there but encountered an issue I detailed in https://github.com/tizonia/tizonia-openmax-il/issues/652. Curious to see what you come up with and see if you manage to avoid/fix that issue!

**Comment by matthewarmand** [comment]
@evilmtv , @tizonia helped me resolve my issue so my `Dockerfile` conversion PR is up at https://github.com/tizonia/docker-tizonia/pull/14 if you'd be interested in looking at it.
