### ISSUE TITLE
youtube-dl - No video format found

### ISSUE THREAD

**Issue by esturniolo** [tizonia/docker-tizonia#18]
### Description

youtube-dl has some problems to run the music now.
In almost all cases I get the following:
`ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

I don't know if there someu pdate from youtube-dl side that affects Tizonia.

### Steps to Reproduce

Use the [Documentation Page Youtube examples](https://docs.tizonia.org/manual/youtube.html)

`$ ./docker-tizonia --youtube-audio-mix-search 'the final countdown'`

`$ ./docker-tizonia --youtube-audio-channel-playlist 'UCGJdzJQ3R1BpahSvcFq23HA masters of metal'`

**Expected behavior:**

Play music without youtube-dl errors.

**Actual behaviour:**

I get `ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Reproduces how often:**

It depend of the track. But in tracks where this happens, happens all time.

### Versions

Debug Info:
            * [Linux@5.4.0-33-generic-#37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020]
            * [Boost 1_65_1]
            * [TagLib 1.11.1]
            * [MediaInfoLib - v17.12]

### Installation Method Used

Docker image.

### Additional Information

Thanks for create Tizonia.

**Comment by matthewarmand** [comment]
Hi @esturniolo , thanks for the detailed report! Looks like a newer version of `youtube-dl` is available so I've upgraded that dependency in https://github.com/tizonia/docker-tizonia/commit/9eb99416fe868c4cfc06e385dea6e8c23d133c97. The [image on dockerhub](https://hub.docker.com/r/tizonia/docker-tizonia/tags) should be updated shortly; alternatively you can also build the image yourself by cloning this repo and using [`build.sh`](https://github.com/tizonia/docker-tizonia/blob/master/build.sh) and then running the [`docker-tizonia`](https://github.com/tizonia/docker-tizonia/blob/master/docker-tizonia) helper script as normal.

**Comment by matthewarmand** [comment]
@esturniolo the `latest` [image on dockerhub](https://hub.docker.com/r/tizonia/docker-tizonia/tags) has been updated, I pulled it down and tested it and the issue looks to be resolved. Feel free to pull the new image down with `docker pull tizonia/docker-tizonia:latest` and test it out.

Closing this issue for now, feel free to comment here if you're still experiencing any issues
