### ISSUE TITLE
Connection refused pactl on Mac

### ISSUE THREAD

**Issue by jrejaud** [tizonia/docker-tizonia#21]
I'm following the mac install instructions and running:

`pactl list short sinks`

returns the following Error:

```
W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```

I'm using pulseaudio 13.0.1 (downloaded via Brew):

```
W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
pulseaudio 13.0
```

**Comment by matthewarmand** [comment]
HI @jrejaud, thanks for the issue! I'm not a Mac user myself so I won't be able to reproduce this, but glancing around at other issues I found your error message at https://github.com/Homebrew/homebrew-core/issues/30062.  It sounds like you're probably already on the latest `Pulseaudio` version supplied by `brew`, but you might want to run a `brew upgrade` just to be sure there hasn't been a new version. 

If the issue persists, you might consider opening an issue with [Homebrew](https://github.com/Homebrew/homebrew-core)

Let me know if you're still having issues after `brew upgrade`

**Comment by jrejaud** [comment]
Hi @matthewarmand, I've followed the instructions provided there, no changes though.

This seems to be an issue with Pulseaudio/ brew, not your docker-tizonia, so I'll close this issue.

Thanks for the help though 👍 

mps-youtube has been very unreliable for a while now, so I think Mac's user's interest in Tizonia will only increase in the near future.

I'll let you know if/ when I get it working.

**Comment by matthewarmand** [comment]
Sounds great! Keep me posted, good luck!
