### ISSUE TITLE
Home directory not accessible: Permission denied

### ISSUE THREAD

**Issue by Rkubinski** [tizonia/docker-tizonia#22]
I seem to keep having this issue, seems to be related to pulse audio. Any thoughts ?

**Comment by matthewarmand** [comment]
Hi @Rkubinski, thanks for the issue. First off, you should always be careful pasting screenshots in issues like this as you've specified your Spotify credentials in the command line. When pasting an image like this it's best to block out sensitive credentials, especially your password. Alternatively you can paste the command line and output in a text/code snippet and redact any sensitive information. 

Next, to your specific issue, I see you're running your own `run - it` command. If you notice in this repo (and I believe its documented on DockerHub as well) there is a [`docker-tizonia`helper script](https://github.com/tizonia/docker-tizonia/blob/master/docker-tizonia) which does some crucial volume mapping to connect Pulse inside the running container to the host machine's system. This might be part of what you're experiencing, or there's another of those volume mappings that is needed elsewhere.

The recommended path is to use that helper script and pass the Tizonia arguments to it, as it supports most use cases as far as I'm aware; if you'd prefer not to do that for whatever reason, I would use that script as a starting point to make sure the container and your system cooperate appropriately. 

Let me know if any of that in particular solves your issue, and also if you continue to have problems. And you may consider editing your original post to redact that images with your creds (and also maybe changing your Spotify password just in case)

**Comment by Rkubinski** [comment]
@matthewarmand thanks for the call out, totally didnt notice that, going to change my password now lol, big mistake on my part. 
Got it, so I will clone the github repo and then run the builder script and get back to you on whether it works ! thanks for the quick response!

**Comment by Rkubinski** [comment]
@matthewarmand that fixed it, have to keep in mind to not run docker as sudo though. 
had to run the two commands:
sudo usermod -aG docker $USER
newgrp docker 
Before I could run the docker command without sudo.
Thanks again!

**Comment by matthewarmand** [comment]
Yep, that's part of the [installation process on Linux](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) for Docker.

Glad it helped!
